# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Project
	pod 'GoogleMaps'
	pod 'Google-Maps-iOS-Utils'
  target 'Project-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
